
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/gdscTest
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true